AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AWSSNSTopic:
    Properties:
      Subscription:
        Endpoint: kaplay4@gmail.com
        Protocol: email
    ResourceName: HelloWorldTopic
    Type: AWS::SNS::Topic
  AWSServerlessFunction:
    Properties:
      CodeUri: s3://ayhans-lambdas/084b55658168cf644d0923ea8c301843
      Environment:
        Variables:
          SNS_TOPIC_ARN:
            Ref: HelloWorldTopic
      Events:
        Api:
          EventName: HelloWorldApi
          Properties:
            Method: GET
            Path: /
          Type: Api
      Handler: index.handler
      Policies:
        SNSPublishMessagePolicy:
          Type: SNSPublishMessagePolicy
          TopicNameIntr:
            Fn::GetAtt: [HelloWorldTopic, TopicName]
      Runtime: nodejs8.10
    ResourceName: HelloWorldFunction
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
